### PR TITLE
Fixed duplicate employee bug

### LINKED ISSUE #165: Uncaught exception when trying to clockIn invalid names
**Describe the bug**
When trying to clockIn using an invalid name, the exception message "Index -1 out-of-bounds for length 4" is shown on screen.

**To Reproduce**
1. Execute the command `clockIn 3`

**Expected behavior**
An error message of some sort that explains that this is an invalid command appears.

**Screenshots**
image

<hr>

**Reported by:** @nianfei97
**Severity:** `Low`

<sub>[original: nusCS2113-AY1819S1/pe-1#550]</sub>

### PR DESCRIPTION
**Pull request by kianhong95**
Resolves #165

### CODE REVIEW

File: src/seedu/addressbook/data/employee/UniqueEmployeeList.java [hunk 1]
```diff
@@ -75,10 +75,12 @@ public UniqueEmployeeList(UniqueEmployeeList source) {
...
     /**
-     * Checks if the list contains an equivalent employee as the given argument.
+     * Checks if the list contains an employee that already exists in Rms.
      */
-    public boolean contains(ReadOnlyEmployee toCheck) {
-        return employeeInternalList.contains(toCheck);
+    public boolean containsDuplicate(ReadOnlyEmployee toCheck) {
+        return employeeInternalList.stream()
+        .filter(o -> o.getName().toString().toLowerCase()
+                .equals(toCheck.getName().toString().toLowerCase())).findFirst().isPresent();
```
Comment (px1099) [inline src/seedu/addressbook/data/employee/UniqueEmployeeList.java]: Need to improve readability.
Try splitting it into multiple lines/methods.

**Review by px1099 — CHANGES_REQUESTED** [review]

File: src/seedu/addressbook/data/employee/UniqueEmployeeList.java (hunk 1 above)
Comment (kianhong95) [reply src/seedu/addressbook/data/employee/UniqueEmployeeList.java]: Not possible to condense into lesser methods as it would be too complicated. Instead split it into more lines based on each method.

**Review by px1099 — APPROVED** [review]

**Comment by px1099** [comment]
Resolve #162, #159 
Please update UG-DG to state that duplicate employee names are not allowed
